### ISSUE TITLE
Doesn't work when versions are of the form 3.5.8.29

### ISSUE THREAD

**Issue by vivekpd15** [dojeda/poetry2conda#8] opened 2020-06-01 21:32 UTC
First of all great work. This looks amazing.

Here is the issue I found:

Tried installing opencv-python-headless = "^3.4.8.29"

Received `ValueError: Invalid simple block '^3.4.8.29'`

**Comment by dojeda** [comment] 2020-06-02 07:57
Hi @vivekpd15 , this seems like a duplicate of issue #3. 
I have just released version 0.3.0 which addresses this issue. Please let me know if that works for you.

**Comment by vivekpd15** [comment] 2021-06-27 11:21
This is fixed

**Closed as completed** 2021-06-27 11:21 UTC
